language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository

script:
   - emulator -avd test -no-skin -no-audio -no-window &
   - android-wait-for-emulator
   - ./gradlew build connectedCheck